### ISSUE TITLE
Could this be shut down by Instagram?

### ISSUE THREAD

**Issue by brendanoneill55** [EdouardCourty/user-instagram#19]
Hi, thanks for developing this, it is extremely handy. I just wanted to see if you had any idea about what Instagram's attitudes towards these scrapers. I'm creating an app which needs Instagram info and the Basic API is a pain. Do you think there is a relatively high probability that Instagram will be able to shut off access to APIs such as these or do you think it's secure? 

This may be a stupid question but would love to get your opinion on it as the developer.

**Comment by foxshark** [comment]
Yes, almost certainly. Instagram has a full featured API for exposing all of the data that you are looking for, however it is quite unlikely that you qualify to get access to it. Using tools - such as this repo - to back into an equivalent data set are, by their nature, temporary until Instagram changes what the expose access to.

**Comment by EdouardCourty** [comment]
Hey, sorry for the late response.

Instagram's API used to be public, but got shutdown because of abuses by the users.
To me there are no solution but this kind of scrapper. The handy part is that sometimes the structure of the response changes and the wrappers (such as this one) has to be updated.

I think this one is on the top of IG scrappers on NPM, and I keep it updated whenever it needs to.

But anyway, it's not an "Official" API, so it's not 100% safe.
