### ISSUE TITLE
Error when deploying severless function 

### ISSUE THREAD

**Issue by qvbreugel** [EdouardCourty/user-instagram#30]
Hi!

First of all, thank you for creating this library!
Unfortunately, I cannot get it to work in production.

I'm working on a Next.JS application and use this library inside of a serverless function.
When I'm testing it locally, everything seems to work fine. 

However, when I deploy the application using Vercel, I get the following error:
`An error occured while fetching data for user boexclusives. Maybe this user does not exist ?`

Do you have any idea why this is happening?

Thanks in advance!

**Comment by matthewlu341** [comment]
This is happening to me locally as well.

**Comment by EdouardCourty** [comment]
Hello, you're being IP restricted by Instagram, this happens if you send too many requests within a small amount of time. I don't know the exact time range, but this problem is common and normal, there is no way to fix it.

However, thanks for your message, it's always nice to have feedback from users !
I tried to bypass this by setting human-like headers, and sending the request through a scriptable browser like pupeeter, without any results.
Also, some VPS providers / hosting services happen to have their IP ranges restricted at all times, making the production servers unable to use this module. 

Try using a proxy !
